name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Upload code
        uses: actions/checkout@v4

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
        shell: bash

      - name: Deploy to server
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USERNAME }}
          APP_DIR: "/root/sector_tech"
          PORT: ${{ secrets.PORT }}
          G_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'

          # Ensure essential variables are set
          if [[ -z "$APP_DIR" || -z "$USER" ]]; then
            echo "Error: APP_DIR or USER is not set."
            exit 1
          fi

          # Ensure the deployment directory exists and is owned by the user
          sudo mkdir -p $APP_DIR
          sudo chown -R $USER:$USER $APP_DIR

          # Clone or update the repository
          echo "Cloning or updating repository..."
          if [ ! -d "$APP_DIR/.git" ]; then
            git clone https://${G_TOKEN}@github.com/boburDev/sector-tech-backend.git $APP_DIR
          else
            cd $APP_DIR
            git reset --hard HEAD
            git pull origin main
          fi

          cd $APP_DIR

          # Create .env file
          echo "Generating .env file..."
          cat > .env <<EOL
          PORT=${PORT}
          DB_PASSWORD=${{ secrets.DB_PASSWORD }}
          DB_NAME=${{ secrets.DB_NAME }}
          JWT_SECRET=${{ secrets.JWT_SECRET }}
          JWT_SECRET_USER=${{ secrets.JWT_SECRET_USER }}
          BASE_URL=${{ secrets.BASE_URL }}
          FACEBOOK_APP_ID=${{ secrets.FACEBOOK_APP_ID }}
          FACEBOOK_APP_SECRET=${{ secrets.FACEBOOK_APP_SECRET }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_CALLBACK_URL=${{ secrets.GOOGLE_CALLBACK_URL }}
          FACEBOOK_CALLBACK_URL=${{ secrets.FACEBOOK_CALLBACK_URL }}
          SESSION_SECRET=${{ secrets.SESSION_SECRET }}
          LINKEDIN_ID=${{ secrets.LINKEDIN_ID }}
          LINKEDIN_SECRET=${{ secrets.LINKEDIN_SECRET }}
          LINKEDIN_CALLBACK_URL=${{ secrets.LINKEDIN_CALLBACK_URL }}
          YANDEX_CLIENT_ID=${{ secrets.YANDEX_CLIENT_ID }}
          YANDEX_CLIENT_SECRET=${{ secrets.YANDEX_CLIENT_SECRET }}
          YANDEX_CALLBACK_URL=${{ secrets.YANDEX_CALLBACK_URL }}
          EOL

          EOF
        shell: bash

