- name: Deploy to server
  env:
    HOST: ${{ secrets.HOST }}
    USER: ${{ secrets.USERNAME }}
    APP_DIR: /sector_tech
    PORT: ${{ secrets.PORT }}
    G_TOKEN: ${{ secrets.G_TOKEN }}
  run: |
    ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
    ssh $USER@$HOST "
      if [ ! -d $APP_DIR ]; then
        mkdir -p $APP_DIR
        git clone https://${G_TOKEN}@github.com/boburDev/sector-tech-backend.git $APP_DIR
      else 
        cd $APP_DIR
        git pull origin main
      fi
      
      cd $APP_DIR
      
      echo 'PORT=${PORT}
      DB_PASSWORD=${{ secrets.DB_PASSWORD }}
      DB_NAME=${{ secrets.DB_NAME }}
      JWT_SECRET=${{ secrets.JWT_SECRET }}
      JWT_SECRET_USER=${{ secrets.JWT_SECRET_USER }}' > .env
      
      npm install

      echo 'Starting Build Process...'
      npm run build || { echo 'Build failed!'; exit 1; }

      if [ ! -f dist/index.js ]; then
        echo 'ERROR: dist/index.js not found!'
        exit 1
      fi

      echo 'Restarting PM2 process...'
      pm2 restart sector_tech || pm2 start dist/index.js --name sector_tech
    "
  shell: bash
