name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Upload code
        uses: actions/checkout@v4

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
        shell: bash

      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} "echo 'SSH Connection Successful'"

      - name: Deploy to server
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USERNAME }}
          APP_DIR: /root/sertor_technology/sector-tech-backend
          PORT: ${{ secrets.PORT }}
          G_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
          if [[ -z "$APP_DIR" || -z "$USER" ]]; then
            echo "Error: APP_DIR or USER is not set."
            exit 1
          fi

          sudo mkdir -p $APP_DIR
          sudo chown -R $USER:$USER $APP_DIR

          if [ ! -d "$APP_DIR/.git" ]; then
            rm -rf $APP_DIR
            git clone https://${G_TOKEN}@github.com/boburDev/sector-tech-backend.git $APP_DIR
          else 
            cd $APP_DIR
            git reset --hard HEAD
            git pull origin main
          fi

          cd $APP_DIR

          npm install
          npm run build || { echo "Build failed!"; exit 1; }

          if [ ! -f "dist/index.js" ]; then
            echo "Error: dist/index.js not found!"
            exit 1
          fi

          pm2 delete sector_tech || true
          pm2 start dist/index.js --name sector_tech
          EOF
        shell: bash
