name: Deploy to VPS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Upload code
        uses: actions/checkout@v4

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Deploy to server
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USERNAME }}
          APP_DIR: /root/sector_tech  # ✅ Change deployment directory
          PORT: ${{ secrets.PORT }}
          G_TOKEN: ${{ secrets.G_TOKEN }}
        run: |
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          ssh $USER@$HOST "
            sudo mkdir -p $APP_DIR
            sudo chown -R \$USER:\$USER $APP_DIR  # ✅ Ensure correct permissions

            if [ ! -d $APP_DIR/.git ]; then
              git clone https://${G_TOKEN}@github.com/boburDev/sector-tech-backend.git $APP_DIR
            else 
              cd $APP_DIR
              git config --global credential.helper 'cache --timeout=3600'
              git config --global user.email 'github-actions@github.com'
              git config --global user.name 'GitHub Actions'
              git pull https://${G_TOKEN}@github.com/boburDev/sector-tech-backend.git main
            fi

            cd $APP_DIR

            echo 'PORT=${PORT}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ secrets.DB_NAME }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_SECRET_USER=${{ secrets.JWT_SECRET_USER }}' > .env

            npm install
            npm run build
            pm2 restart sector_tech || pm2 start dist/index.js --name sector_tech
          "
        shell: bash
