name: Deploy to VPS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Upload code
        uses: actions/checkout@v4

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash
      - name: Deploy to server
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USERNAME }}
          APP_DIR: /sector_tech
          PORT: ${{ secrets.PORT }}
        run: |
          ssh-keyscan -H $HOST >> ~/.ssh/known_hosts
          ssh $USER@$HOST "
            if [ ! -d $APP_DIR ]; then
              mkdir -p $APP_DIR
              git clone https://github.com/boburDev/sector-tech-backend.git $APP_DIR
              cd $APP_DIR
               echo 'PORT=${PORT}
               DB_PASSWORD=${{ secrets.DB_PASSWORD }}
               DB_NAME=${{ secrets.DB_NAME }}
               JWT_SECRET=${{ secrets.JWT_SECRET }}
               JWT_SECRET_USER=${{ secrets.JWT_SECRET_USER }}' > .env
            else 
              cd $APP_DIR
              git pull origin main 
            fi
            npm install
            npm run build
            pm2 restart sector_tech || pm2 start dist/index.js --name sector_tech
          "
        shell: bash